### ISSUE TITLE
remove .dp__input styles  and replace them by tailwind css classes 

### ISSUE THREAD

**Issue by scramatte** [Vuepic/vue-datepicker#1022]
Hi,

I'm currently integrating vue-datepicker int laravel nova 4.
I need to remove completly  ".dp__input" styles and use tailwind classes instead.

Can you give me some hand with this issue?

Regards

**Comment by scramatte** [comment]
Sorry for the noise ...
I've fixed with the following :
 
```css
<style>
.dp__input {
   font-size: unset;      
   font-familly: unset; 
   border: unset; 
}
</style>
```
