### ISSUE TITLE
Transition example

### ISSUE THREAD

**Issue by cpkuo** [Vuepic/vue-datepicker#18]
I'm reading the documentation about transitions:

"To configure you own, please check the Vue documentation and provide a transition name in the prop". Is there an example on how to do this? I've tried to wrap the component in a transition tag as well as given the datetimepicker component a prop of transitionName="fade" but I can't seem to get it to work. Thanks!

**Comment by Jasenkoo** [comment]
I will use the transition example provided in the [vue docs](https://vuejs.org/guide/built-ins/transition.html#css-based-transitions)

Firstly define your custom transition in the `CSS` file

```css
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
```

Then pass that name for the targeted part e.g.

```vue
<template>
  <Datepicker :transitions="{ next: 'fade', previous: 'fade' }" />
</template>
```

This will animate the calendar when going to the next and previous month using `fade` transition
