### ISSUE TITLE
Select button and selected date ring stay blue

### ISSUE THREAD

**Issue by PatrickKaim** [Vuepic/vue-datepicker#460]
I've enabled dark mode and scoped style, but the select. button stays blue instead of the set primary color.
What should I do to change the color of the select button and selected date ring?
<img width="269" alt="Scherm­afbeelding 2023-06-30 om 08 06 53" src="https://github.com/Vuepic/vue-datepicker/assets/18009623/7504b6ec-3546-46fe-867d-7d67daded34b">

**Comment by Jasenkoo** [comment]
In your parent component or global CSS file, define a class

```css
.dp__theme_dark {
   --dp-primary-color: /*any color you want */ #005cb2;
   --dp-primary-text-color: /*if the text contrast is not good, you can adjust this variable also*/ #ffffff;
}
```
