### ISSUE TITLE
Toggle month/year overlay from custom component

### ISSUE THREAD

**Issue by tereza-k** [Vuepic/vue-datepicker#52]
Hello,

thank you for a great datepicker.
I am trying to implement **custom `monthYearComponent`** where it would be pretty much the same as the default one, but **Month text and Year text would be one button**, instead of two separate buttons.

When the **button is clicked**, the **default month overlay would be shown**.
When month is selected, the default year overlay would be shown.
When year is selected, overlay is closed back to calendar.

![image](https://user-images.githubusercontent.com/82960518/169796987-5f5ad5ab-796c-4bd4-9bb0-5188a5299eb4.png)

Is there **any toggle method** I could use?
I have tried to use provide/inject, so **I am able to detect the click** in custom `monthYearComponent`. And **I do handle the event** in the parent component. But **I am lost as how to toggle the Month overlay** and later on the Year overlay.
I have tried updating the prop `monthPicker` to `true`. And the overlay does change, but the content is empty.
![image](https://user-images.githubusercontent.com/82960518/169797706-475d1ac5-9df5-44f2-93f7-cba798928967.png)

What I have tried:

**Parent:**
```
<Datepicker v-model="date" :monthPicker="monthPicker" />


const monthPicker = ref(false);
const setOverlay = (type) => {
    if (type === "month") monthPicker.value = true;
};

provide('setOverlay', {
  setOverlay
});
```

**Custom component:**

```
<div @click="setOverlay("month")">{{ months[month].text }} {{ year }}</div>

const { setOverlay} = inject('setOverlay');
```
But I am lost as what to do in the `setOverlay` function to toggle on the month overlay.

Thank you for your help.

**Comment by Jasenkoo** [comment]
First of all tnx 😄. 

When you use a custom component, the part is replaced along with the pick logic such as overlays:

![](https://i.imgur.com/ruMbccr.png)

Overlays are part of the built-in monthYearPicker component. The overlay uses the following style:

```css

.dp__overlay {
  position: absolute;
  overflow-y: auto;
  width: 100%;
  height: 100%;
  background: var(--dp-background-color);
  top: 0;
  left: 0;
  transition: opacity 1s ease-out;
  z-index: 99999;
  font-family: $dp__font_family;
  color: var(--dp-text-color);
  box-sizing: border-box;
}

.dp__overlay_container {
  display: flex;
  height: 100%;
  flex-direction: column;
}
```

Then in the HTML

```html
<div class="dp__overlay ">
  <div class="dp__overlay_container">
     <!--  Ovelay content goes here -->
  </div>
</div>
```

You will place this overlay in your custom component and use a simple `v-show` or `v-if` when needed. It will span across the calendar.

I will see to add support for just a header instead of all logic replacement.
