### ISSUE TITLE
Add new CSS variables to control `dp__range_between` colors independently

### ISSUE THREAD

**Issue by ayrtonandino** [Vuepic/vue-datepicker#608]
**Is your feature request related to a problem? Please describe.**
Add new css variables to control colors in `dp__range_between` class, which will allow for better themeing posibilities.
Currently it uses `--dp-hover-color` for background and border colors.

**Describe the solution you'd like**
Add 2 new variables, `--dp-range-between-dates-background-color` and `--dp-range-between-dates-text-color` that inherit colors from `--dp-hover-color` to maintain backwards compatibility.

**Describe alternatives you've considered**
Add variables to `.dp__theme_light` and `.dp__theme_dark`

```css
.dp__theme_light {
    --dp-hover-color: #f3f3f3;
    --dp-range-between-dates-background-color: var(--dp-hover-color, #f3f3f3); /* <- With Fallback value */
    --dp-range-between-dates-text-color: var(--dp-hover-color, #f3f3f3);
    ...
}
```

Change `.dp__range_between` to:

```css
.dp__range_between {
    color: var(--dp-range-between-dates-text-color);
    background: var(--dp-range-between-dates-background-color);
    border: 1px solid var(--dp-range-between-dates-background-color);
    border-radius: 0;
}
```
