### ISSUE TITLE
Style of input placeholder does not change

### ISSUE THREAD

**Issue by jduncanRadBlue** [Vuepic/vue-datepicker#815]
**Describe the bug**
Trying to change the color of the input placeholder and it doesn't change.  The color only applies to the value of the date selected, not the placeholder text.

**To Reproduce**
```
<VueDatePicker
  class="mt-2"
  :state="dateValid"
  placeholder="Select Start Date"
  input-class-name="dp-custom-input"
  :min-date="new Date()"
  v-model="request.startTime"
  @update:model-value="checkDateValid"
  :dark="theme.global.current.value.dark"
></VueDatePicker>
```
custom style:
```
<style lang="scss">
.dp-custom-input {
  box-shadow: 0 0 6px #1976d2;
  color: #1976d2;

  &:hover {
    border-color: #1976d2;
  }
}
</style>

```
Is there a way to style the input's placeholder text?

**Comment by Jasenkoo** [comment]
This is a css question, but to style placeholder, you need to actually use a placeholder selector

```scss
&::placeholder {
   color: #1976d2;
}
```

specifically

```scss

.dp-custom-input {
    box-shadow: 0 0 6px #1976d2;
    color: #1976d2;

    &::placeholder {
        color: #1976d2;
    }

    &:hover {
        border-color: #1976d2;
    }
}
```
